spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pirs_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
  
  spring:
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379