spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pirs_db
    username: postgres
    password: ${DB_PASSWORD}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true