server:
  port: 8080

spring:
  application:
    name: tool

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/post_incident_review}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: false
    locations: classpath:db/migration

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 60000

  mail:
  host: smtp.gmail.com
  port: 587
  username: yourgmail@gmail.com
  password: your16characterapppassword
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true

jwt:
  secret: ${JWT_SECRET:mysecretkeymysecretkeymysecretkey12345}
  expiration: ${JWT_EXPIRATION:86400000}